# Generated by Django 6.0.7 on 2026-08-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
