# Generated by Django 6.0.7 on 2026-08-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_resolution_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Pothole', 'Pothole'), ('Garbage', 'Garbage'), ('Street Light', 'Street Light'), ('Water Leakage', 'Water Leakage'), ('Drainage', 'Drainage'), ('Road Damage', 'Road Damage'), ('Traffic Signal', 'Traffic Signal'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('Road Department', 'Road Department'), ('Sanitation Department', 'Sanitation Department'), ('Water Department', 'Water Department'), ('Electrical Department', 'Electrical Department'), ('Traffic Department', 'Traffic Department'), ('General', 'General')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='complaints.complaint')),
            ],
        ),
    ]
